 const governorates = [
  { govarName: 'القاهرة', govId: 1 , govEngName:"" ,psh: 5},
  { govName: 'الجيزة', govId: 2 , govEngName:"" ,psh: 5},
  { govName: 'الإسكندرية', govId: 3 , govEngName:"" ,psh: 5},
  { govName: 'الدقهلية', govId: 4 , govEngName:"" ,psh: 5},
  { govName: 'الشرقية', govId: 5 , govEngName:"" ,psh: 5},
  { govName: 'المنوفية', govId: 6 , govEngName:"" ,psh: 5},
  { govName: 'الغربية', govId: 7 , govEngName:"" ,psh: 5},
  { govName: 'كفر الشيخ', govId: 8 , govEngName:"" ,psh: 5},
  { govName: 'دمياط', govId: 9 , govEngName:"" ,psh: 5},
  { govName: 'البحيرة', govId: 10 , govEngName:"" ,psh: 5},
  { govName: 'الإسماعيلية', govId: 11 , govEngName:"" ,psh: 5},
  { govName: 'بورسعيد', govId: 12 , govEngName:"" ,psh: 5},
  { govName: 'السويس', govId: 13 , govEngName:"" ,psh: 5},
  { govName: 'شمال سيناء', govId: 14 , govEngName:"" ,psh: 5},
  { govName: 'جنوب سيناء', govId: 15 , govEngName:"" ,psh: 5},
  { govName: 'بني سويف', govId: 16 , govEngName:"" ,psh: 5},
  { govName: 'الفيوم', govId: 17 , govEngName:"" ,psh: 5},
  { govName: 'المنيا', govId: 18 , govEngName:"" ,psh: 5},
  { govName: 'أسيوط', govId: 19 , govEngName:"" ,psh: 5},
  { govName: 'سوهاج', govId: 20 , govEngName:"" ,psh: 5},
  { govName: 'قنا', govId: 21 , govEngName:"" ,psh: 5},
  { govName: 'الأقصر', govId: 22 , govEngName:"" ,psh: 5},
  { govName: 'أسوان', govId: 23 , govEngName:"" ,psh: 5},
  { govName: 'الوادي الجديد', govId: 24 , govEngName:"" ,psh: 5},
  { govName: 'مطروح', govId: 25 , govEngName:"" ,psh: 5},
  { govName: 'البحر الأحمر', govId: 26 , govEngName:"" ,psh: 5},
];